name: pokedex_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  mobx: ^2.2.0
  mobx_codegen: ^2.3.0
  flutter_mobx: ^2.0.6+5
  build_runner: ^2.3.3
  dio: ^5.1.2
  flutter_svg: ^2.0.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: PokemonApp
      fonts:
        - asset: fonts/PokemonApp.ttf
